version: "3"

services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:3000"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=hi+websites@alfanjauhari.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - traefik-public

  statementsfetcher:
    image: alfanjauhari/statements-fetcher:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.statementsfetcher.rule=Host(`finance.alfanjauhari.com`)"
      - "traefik.http.routers.statementsfetcher.entrypoints=websecure"
      - "traefik.http.routers.statementsfetcher.tls.certresolver=myresolver"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
